spring.datasource.url=jdbc:mysql://localhost:3306/parksmartdb
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=https://*.app.github.dev
app.remember-me.key=parksmart-codespaces-key
